version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - EnvFiles/.envDb
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    image: api
    container_name: api
    build: crypto-api
    depends_on:
      - db
    env_file:
      - EnvFiles/.envApi
    ports:
      - 5000:5000
    restart: unless-stopped

  ###
  front:
    build: ./client
    container_name: frontend
    env_file:
      - EnvFiles/.envFront
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  db:
    driver: local
