version: '3.8'
services: 
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=crypto
      - MYSQL_ROOT_PASSWORD=db_password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  crypto-api:
    build: ./crypto-api
    container_name: crypto-api
    image: crypto-api
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Crypto2022
      DB_NAME: crypto
    links:
      - db
    volumes:
      - ./:/src

  client: 
    build: ./client
    container_name: client_frontend
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
