version: '3.8'
services: 
  db:
    image: mysql:8.0
    restart: always
    environment: 
      MYSQL_HOST: '127.0.0.1'
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: crypto
    ports:
      - "3306:3306"
    expose:
      - 3306
    container_name: basic-mysql
    volumes:
      - ./tmp/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: db_password
    ports:
      - "8080:80"
    expose:
      - 8080
    depends_on:
      - db

  crypto-api:
    build: ./crypto-api
    container_name: crypto-api
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./crypto-api:/usr/src/app
    restart: unless-stopped


  client: 
    build: ./client
    container_name: client_frontend
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
      