version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=crypto
      - MYSQL_ROOT_PASSWORD=db_password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  api:
    image: api
    container_name: api
    build: crypto-api
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: db_password
      DB_NAME: crypto
    depends_on:
      - db
    restart: unless-stopped

  front:
    build: ./client
    container_name: frontend
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  db:
    driver: local
