name: Pray4Elixir
run-name: Deploy production
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ['test-vuejs', 'test-elixir']
    name: Deploy to server
    steps:
      - name: Deploy to production and compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Pray4Elixir
            git checkout prod
            git pull
            docker compose down
            docker system prune -a -f
            docker compose up -d --build
    
  mirror:
    runs-on: ubuntu-latest
    needs: deploy
    name: Mirror on epitech repo
    steps:
      - name: Push on remote repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -R ~/T-POO-700-NCE_2
            git clone git@github.com:EpitechMscProPromo2024/T-POO-700-NCE_2.git
            cd ~/T-POO-700-NCE_2
            cp -R ../Pray4Elixir/* .
            git add .
            git commit -m "Push mirror"
            git push