# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/Mulherbe/cryptoWeb"
          source_branch: "main"
          destination_repo: "https://github.com/EpitechMscProPromo2024/T-WEB-700-NCE_10"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_KEY }} # optional
