name: Pray4Elixir
run-name: Deploy production
on:
  push:
    branches:
      - main
      
jobs:
  test-vuejs:
    name: Test VueJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo sur le container
        uses: actions/checkout@v3
        with:
          ref: prod
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: '19.0.0'
      - name: Ls pwd
        run: pwd && ls
      - name: Install dependencies
        run: cd tmanager && npm install
 